### PR TITLE
Added extended xml comments to the FromDouble* methods (WIP)

### PR DESCRIPTION
**Pull request by lipchev**
* Fraction.ConvertFrom split into Fraction.ConvertFromNumber and Fraction.ConvertFromString (no changes to the code)
* replaced the xml comments from the FromDouble* functions (providing details about the possible caveats with each one)
* replaced the Readme sections regarding the Creation from double with an extended version (including the new overload)

### CODE REVIEW

**Comment by lipchev** [comment]
oh, did i miss some change in the ConvertFrom, why is this giving me a conflict.. 😕

**Comment by danm-de** [comment]
Sorry, I do not want to split those files.

**Comment by danm-de** [comment]
As a non-native English speaker, I think the documentation improvement is great. Unfortunately it's mixed up in this branch.

**Comment by lipchev** [comment]
Sure, no problem- I had messed up the branch anyway. I'll create a new one..

**Comment by danm-de** [comment]
> Sure, no problem- I had messed up the branch anyway. I'll create a new one..

Cool, thanks!

**Pull request closed without merging**
