### PR TITLE
Default to value equality (review) (WIP)

### PR DESCRIPTION
**Pull request by lipchev**
Here are the results of the `ComparisonBenchmarks`. 

image

There isn't much we can do about the increase of the `GetHashCode` (note that the relative increase for the normalized fraction looks significant but in fact we're talking an absolute increase from 7 ns to 10 ns).
Here are the absolute times:

image

As for the `Equals` - not checking the `_normalizationNotApplied` is clearly hurting the case when comparing normalized fractions, but:
1) The user can optimize this scenario using the `FractionStrictEqualityComparer`
2) I think there is still one allocation-case that we can avoid- for both the the `CompareTo` and `Equals` methods - using the recently-added `MultiplyTerms` method
3) Same as with the `BasicMathOperationBenchmarks` - we're mostly only benchmarking non-standard values here. We should probably add an extra benchmark parameter (`Normalized') which, should benchmark the performance of the more standard values such as "1.35"

I'm going to try out 2) and see if this would improve the `large-integer` and `1/large-integer` cases

### CODE REVIEW

**Comment by lipchev** [comment]
Hmm, not sure why AppVeyon is failing now- here's the relative change two the benchmarks when using the `MultiplyTerms` (replaced both `Equals` and `CompareTo`):

image

And the absolute times:

image

The extra allocations didn't go away (I think it maybe because the value is negative), but still there is a visible change on the integer cases (and no difference otherwise).

**Comment by lipchev** [comment]
Ok, so here's explanation for the extra allocation. Remember how I said in #65 that the performance characteristics of the reduced fraction w.r.t. _trivial_ BigIntegers, and how it's like a [staircase function](https://mathworld.wolfram.com/StaircaseFunction.html) well, here's the very neat benchmark that shows just that (all parameters are non-normalized):
```
    [Benchmark(Baseline = true)]
    [ArgumentsSource(nameof(Operands))]
    public bool Equals(Fraction a, Fraction b) {
        return a.Equals(b);
    }

    [Benchmark]
    [ArgumentsSource(nameof(Operands))]
    public bool StrictlyEquals(Fraction a, Fraction b) {
        return FractionComparer.StrictEquality.Equals(a.Reduce(), b.Reduce());
    }
```

I should have actually used the name `IsEquivalent` for the second one, that would have very appropriate. 😄 

<html>
<body>


Method | Job | Runtime | a | b | Mean | Error | StdDev | Ratio | RatioSD | Gen0 | Allocated | Alloc Ratio
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Equals | ShortRun-.NET 8.0 | .NET 8.0 | 42/-96 | 36/-96 | 4.513 ns | 0.2609 ns | 0.0143 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET 8.0 | .NET 8.0 | 42/-96 | 36/-96 | 53.872 ns | 1.2312 ns | 0.0675 ns | 11.94 | 0.04 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 42/-96 | 36/-96 | 20.541 ns | 0.8919 ns | 0.0489 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 42/-96 | 36/-96 | 201.907 ns | 12.0909 ns | 0.6627 ns | 9.83 | 0.05 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET 8.0 | .NET 8.0 | -1000(...)000/1 [41] | 1/1000000000000 | 25.146 ns | 0.4613 ns | 0.0253 ns | 1.00 | 0.00 | 0.0029 | 48 B | 1.00
StrictlyEquals | ShortRun-.NET 8.0 | .NET 8.0 | -1000(...)000/1 [41] | 1/1000000000000 | 20.834 ns | 0.7147 ns | 0.0392 ns | 0.83 | 0.00 | - | - | 0.00
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | -1000(...)000/1 [41] | 1/1000000000000 | 70.580 ns | 4.7334 ns | 0.2595 ns | 1.00 | 0.00 | 0.0076 | 48 B | 1.00
StrictlyEquals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | -1000(...)000/1 [41] | 1/1000000000000 | 65.324 ns | 3.4192 ns | 0.1874 ns | 0.93 | 0.00 | - | - | 0.00
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET 8.0 | .NET 8.0 | -1024/1 | -1/1024 | 9.757 ns | 0.3215 ns | 0.0176 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET 8.0 | .NET 8.0 | -1024/1 | -1/1024 | 21.657 ns | 0.5853 ns | 0.0321 ns | 2.22 | 0.01 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | -1024/1 | -1/1024 | 36.129 ns | 4.2621 ns | 0.2336 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | -1024/1 | -1/1024 | 71.550 ns | 3.2844 ns | 0.1800 ns | 1.98 | 0.01 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET 8.0 | .NET 8.0 | -45/1 | 1/6 | 9.999 ns | 1.1166 ns | 0.0612 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET 8.0 | .NET 8.0 | -45/1 | 1/6 | 20.422 ns | 2.1154 ns | 0.1160 ns | 2.04 | 0.02 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | -45/1 | 1/6 | 36.017 ns | 0.1226 ns | 0.0067 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | -45/1 | 1/6 | 68.447 ns | 1.0112 ns | 0.0554 ns | 1.90 | 0.00 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET 8.0 | .NET 8.0 | 0/1 | 1/1 | 4.500 ns | 0.2454 ns | 0.0135 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET 8.0 | .NET 8.0 | 0/1 | 1/1 | 22.999 ns | 2.3682 ns | 0.1298 ns | 5.11 | 0.04 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 0/1 | 1/1 | 20.591 ns | 0.2738 ns | 0.0150 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 0/1 | 1/1 | 51.932 ns | 2.2918 ns | 0.1256 ns | 2.52 | 0.01 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET 8.0 | .NET 8.0 | 77/3600 | 37/3600 | 4.534 ns | 0.3046 ns | 0.0167 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET 8.0 | .NET 8.0 | 77/3600 | 37/3600 | 36.328 ns | 0.7132 ns | 0.0391 ns | 8.01 | 0.02 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 77/3600 | 37/3600 | 20.731 ns | 1.2064 ns | 0.0661 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 77/3600 | 37/3600 | 149.725 ns | 46.2720 ns | 2.5363 ns | 7.22 | 0.10 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET 8.0 | .NET 8.0 | 135/1000 | 76/1000 | 3.601 ns | 0.2375 ns | 0.0130 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET 8.0 | .NET 8.0 | 135/1000 | 76/1000 | 54.553 ns | 1.7891 ns | 0.0981 ns | 15.15 | 0.03 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 135/1000 | 76/1000 | 20.703 ns | 0.6829 ns | 0.0374 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 135/1000 | 76/1000 | 211.385 ns | 11.2939 ns | 0.6191 ns | 10.21 | 0.04 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET 8.0 | .NET 8.0 | 27/200 | 19/250 | 16.105 ns | 2.7833 ns | 0.1526 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET 8.0 | .NET 8.0 | 27/200 | 19/250 | 32.350 ns | 1.4965 ns | 0.0820 ns | 2.01 | 0.01 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 27/200 | 19/250 | 55.285 ns | 6.0269 ns | 0.3304 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 27/200 | 19/250 | 133.741 ns | 13.3999 ns | 0.7345 ns | 2.42 | 0.03 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET 8.0 | .NET 8.0 | 42/66 | 36/96 | 16.064 ns | 0.5371 ns | 0.0294 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET 8.0 | .NET 8.0 | 42/66 | 36/96 | 53.126 ns | 8.6338 ns | 0.4732 ns | 3.31 | 0.04 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 42/66 | 36/96 | 55.206 ns | 5.1957 ns | 0.2848 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 42/66 | 36/96 | 199.494 ns | 2.7847 ns | 0.1526 ns | 3.61 | 0.02 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET 8.0 | .NET 8.0 | 70742(...)85248 [33] | 70742(...)70496 [33] | 42.739 ns | 2.2847 ns | 0.1252 ns | 1.00 | 0.00 | 0.0048 | 80 B | 1.00
StrictlyEquals | ShortRun-.NET 8.0 | .NET 8.0 | 70742(...)85248 [33] | 70742(...)70496 [33] | 181.500 ns | 22.6309 ns | 1.2405 ns | 4.25 | 0.03 | 0.0076 | 128 B | 1.60
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 70742(...)85248 [33] | 70742(...)70496 [33] | 113.375 ns | 11.4255 ns | 0.6263 ns | 1.00 | 0.00 | 0.0126 | 80 B | 1.00
StrictlyEquals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 70742(...)85248 [33] | 70742(...)70496 [33] | 315.411 ns | 47.5255 ns | 2.6050 ns | 2.78 | 0.02 | 0.0305 | 193 B | 2.41
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET 8.0 | .NET 8.0 | 245850922/78256779 | NaN | 3.727 ns | 0.0136 ns | 0.0007 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET 8.0 | .NET 8.0 | 245850922/78256779 | NaN | 40.066 ns | 1.9572 ns | 0.1073 ns | 10.75 | 0.03 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 245850922/78256779 | NaN | 19.671 ns | 0.2114 ns | 0.0116 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 245850922/78256779 | NaN | 104.248 ns | 6.8111 ns | 0.3733 ns | 5.30 | 0.02 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET 8.0 | .NET 8.0 | 245850922/78256779 | -∞ | 3.782 ns | 0.3093 ns | 0.0170 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET 8.0 | .NET 8.0 | 245850922/78256779 | -∞ | 39.678 ns | 1.2020 ns | 0.0659 ns | 10.49 | 0.06 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 245850922/78256779 | -∞ | 19.593 ns | 0.4803 ns | 0.0263 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 245850922/78256779 | -∞ | 105.336 ns | 1.4951 ns | 0.0820 ns | 5.38 | 0.00 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET 8.0 | .NET 8.0 | 245850922/78256779 | 0 | 3.982 ns | 0.0800 ns | 0.0044 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET 8.0 | .NET 8.0 | 245850922/78256779 | 0 | 40.216 ns | 1.5677 ns | 0.0859 ns | 10.10 | 0.02 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 245850922/78256779 | 0 | 19.764 ns | 0.6507 ns | 0.0357 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 245850922/78256779 | 0 | 104.707 ns | 0.6014 ns | 0.0330 ns | 5.30 | 0.01 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET 8.0 | .NET 8.0 | 97/1 | 89/1 | 4.645 ns | 3.7411 ns | 0.2051 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET 8.0 | .NET 8.0 | 97/1 | 89/1 | 20.442 ns | 1.2067 ns | 0.0661 ns | 4.41 | 0.20 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 97/1 | 89/1 | 20.691 ns | 0.5459 ns | 0.0299 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 97/1 | 89/1 | 68.462 ns | 7.1939 ns | 0.3943 ns | 3.31 | 0.02 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET 8.0 | .NET 8.0 | 1000/1 | 100/1 | 4.402 ns | 0.1125 ns | 0.0062 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET 8.0 | .NET 8.0 | 1000/1 | 100/1 | 21.013 ns | 3.7481 ns | 0.2054 ns | 4.77 | 0.05 | - | - | NA
  |   |   |   |   |   |   |   |   |   |   |   |  
Equals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 1000/1 | 100/1 | 20.694 ns | 0.6429 ns | 0.0352 ns | 1.00 | 0.00 | - | - | NA
StrictlyEquals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 1000/1 | 100/1 | 68.266 ns | 2.5707 ns | 0.1409 ns | 3.30 | 0.00 | - | - | NA


</body>
</html>

See how there is just one for which the multiplication is actually slower than the GCD reduction, but that just works for the values that would have otherwise crossed the non-trivial boundary (`int.MaxValue`). Its also likely that every subsequent element of the `BigInteger._bits` would have even less effect on the overall performance..

**Comment by lipchev** [comment]
Heads up, I've got a new (quite verbose) implementation of the Equals that eliminates all allocations (for the previously tested values). The trick is that instead of multiplying (introducing/increasing the `_bits`) we instead perform divisions, that usually result in `BigInteger`s that are _trivial_.

```
        var numeratorQuotient = BigInteger.DivRem(numerator1, numerator2, out var remainderNumerators);
        var denominatorQuotient = BigInteger.DivRem(denominator1, denominator2, out var remainderDenominators);
        // if the fractions are equal: numeratorQuotient should be equal to denominatorQuotient
        if (numeratorQuotient != denominatorQuotient) {
            return false;
        }

        // if the fractions are equal: {remainderNumerators / numerator2} should be equal to {remainderDenominators / denominator2}
        if (remainderNumerators.IsZero) {
            // both values should be 0 
            return remainderDenominators.IsZero;
        }

        if (remainderDenominators.IsZero) {
            // both values should be 0 
            return false;
        }
        
        return remainderNumerators * denominator2 == remainderDenominators * numerator2;
```

I'm also doing a lot of value-checking before, in order to get the larger denominator divided by the smaller one, but overall I think this should work more or less the same way for the `CompareTo`.
Here's the result from the `ComparisonBenchmarks`:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/galin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/galin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Method | Job | Runtime | a | b | Mean | Error | StdDev | Gen0 | Allocated
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Equals | ShortRun-.NET   8.0 | .NET   8.0 | -1000(...)00000   [39] | 1/1000000000000 | 14.08   ns | 0.183   ns | 0.010   ns | - | -
Equals | ShortRun-.NET   Framework 4.8 | .NET   Framework 4.8 | -1000(...)00000   [39] | 1/1000000000000 | 28.50   ns | 1.874   ns | 0.103   ns | - | -
Equals | ShortRun-.NET   8.0 | .NET   8.0 | -1024 | -1/1024 | 13.67   ns | 0.761   ns | 0.042   ns | - | -
Equals | ShortRun-.NET   Framework 4.8 | .NET   Framework 4.8 | -1024 | -1/1024 | 26.20   ns | 0.381   ns | 0.021   ns | - | -
Equals | ShortRun-.NET   8.0 | .NET   8.0 | -45 | 1/6 | 13.80   ns | 1.134   ns | 0.062   ns | - | -
Equals | ShortRun-.NET   Framework 4.8 | .NET   Framework 4.8 | -45 | 1/6 | 27.74   ns | 0.466   ns | 0.026   ns | - | -
Equals | ShortRun-.NET   8.0 | .NET   8.0 | 0 | 1 | 14.13   ns | 0.289   ns | 0.016   ns | - | -
Equals | ShortRun-.NET   Framework 4.8 | .NET   Framework 4.8 | 0 | 1 | 23.78   ns | 0.620   ns | 0.034   ns | - | -
Equals | ShortRun-.NET   8.0 | .NET   8.0 | 77/3600 | 37/3600 | 14.47   ns | 1.906   ns | 0.104   ns | - | -
Equals | ShortRun-.NET   Framework 4.8 | .NET   Framework 4.8 | 77/3600 | 37/3600 | 23.81   ns | 1.356   ns | 0.074   ns | - | -
Equals | ShortRun-.NET   8.0 | .NET   8.0 | 27/200 | 19/250 | 21.05   ns | 5.994   ns | 0.329   ns | - | -
Equals | ShortRun-.NET   Framework 4.8 | .NET   Framework 4.8 | 27/200 | 19/250 | 30.65   ns | 1.941   ns | 0.106   ns | - | -
Equals | ShortRun-.NET   8.0 | .NET   8.0 | 88427(...)10656   [31] | 88427(...)21312   [31] | 26.65   ns | 1.978   ns | 0.108   ns | - | -
Equals | ShortRun-.NET   Framework 4.8 | .NET   Framework 4.8 | 88427(...)10656   [31] | 88427(...)21312   [31] | 40.89   ns | 4.236   ns | 0.232   ns | - | -
Equals | ShortRun-.NET   8.0 | .NET   8.0 | 245850922/78256779 | NaN | 13.47   ns | 1.453   ns | 0.080   ns | - | -
Equals | ShortRun-.NET   Framework 4.8 | .NET   Framework 4.8 | 245850922/78256779 | NaN | 23.56   ns | 1.414   ns | 0.077   ns | - | -
Equals | ShortRun-.NET   8.0 | .NET   8.0 | 245850922/78256779 | -∞ | 13.46   ns | 1.066   ns | 0.058   ns | - | -
Equals | ShortRun-.NET   Framework 4.8 | .NET   Framework 4.8 | 245850922/78256779 | -∞ | 26.36   ns | 1.241   ns | 0.068   ns | - | -
Equals | ShortRun-.NET   8.0 | .NET   8.0 | 245850922/78256779 | 0 | 13.09   ns | 0.435   ns | 0.024   ns | - | -
Equals | ShortRun-.NET   Framework 4.8 | .NET   Framework 4.8 | 245850922/78256779 | 0 | 22.72   ns | 0.715   ns | 0.039   ns | - | -
Equals | ShortRun-.NET   8.0 | .NET   8.0 | 12345(...)00000   [36] | 61728(...)00000   [34] | 65.94   ns | 1.588   ns | 0.087   ns | 0.0019 | 32 B
Equals | ShortRun-.NET   Framework 4.8 | .NET   Framework 4.8 | 12345(...)00000   [36] | 61728(...)00000   [34] | 135.89   ns | 2.433   ns | 0.133   ns | 0.0100 | 64 B
Equals | ShortRun-.NET   8.0 | .NET   8.0 | 97 | 89 | 14.43   ns | 1.303   ns | 0.071   ns | - | -
Equals | ShortRun-.NET   Framework 4.8 | .NET   Framework 4.8 | 97 | 89 | 23.82   ns | 0.472   ns | 0.026   ns | - | -
Equals | ShortRun-.NET   8.0 | .NET   8.0 | 1000 | 100 | 14.12   ns | 0.403   ns | 0.022   ns | - | -
Equals | ShortRun-.NET Framework 4.8 | .NET Framework 4.8 | 1000 | 100 | 23.68 ns | 0.439 ns | 0.024 ns | - | -



</body>

</html>

The only allocation here is one that I've added after:
```
// very close fractions: 
yield return [
    new Fraction(12.3456789987654321m),
    new Fraction(12.3456789987654322m)];
```

**Comment by lipchev** [comment]
Lol, I just realized there is a bug in the `CompareTo` method (v8):
<!DOCTYPE html>
<HTML>
<head>
<body>


  | Name | Value | Type
-- | -- | -- | --
  | new Fraction(0.1m).CompareTo(new Fraction(-2, -10, false)) | 1 | int



</body>
</HTML>

**Comment by danm-de** [comment]
> Lol, I just realized there is a bug in the `CompareTo` method (v8):
> 
>  	Name	Value	Type
>  	new Fraction(0.1m).CompareTo(new Fraction(-2, -10, false))	1	int

Nice catch!

**Comment by danm-de** [comment]
I have merged your changes. Feel free to reopen the pull request if further adjustments are necessary. The performance improvements could possibly be added later in version 8.0.1 (or higher) - for me personally the current result is already okay.

**Pull request merged**
